
export GITHUB_OWNER="${GITHUB_OWNER:-${GH_OWNER:-comstrx}}"

export ARCHIVE_DIR="${ARCHIVE_DIR:-${BACKUP_DIR:-/mnt/d/Archive}}"
export ARCHIVE_CAP=1

export SYNC_DIR="${SYNC_DIR:-${MIRROR_DIR:-/mnt/d/Projects}}"
export SYNC_CAP=1

declare -a EMPIRE_TOOLS=(
    "bash:bash"
    "git:git"
    "gh:gh"

    "ssh:openssh-client"
    "scp:openssh-client"

    "rsync:rsync"
    "curl:curl"
    "wget:wget"

    "cat:coreutils"
    "cp:coreutils"
    "mv:coreutils"
    "rm:coreutils"
    "mkdir:coreutils"
    "touch:coreutils"
    "chmod:coreutils"
    "chown:coreutils"
    "basename:coreutils"
    "dirname:coreutils"
    "realpath:coreutils"
    "date:coreutils"
    "sleep:coreutils"
    "base64:coreutils"
    "sha256sum:coreutils"

    "sed:sed"
    "awk:gawk"
    "grep:grep"
    "find:findutils"
    "xargs:findutils"
    "sort:coreutils"
    "head:coreutils"
    "tail:coreutils"
    "tr:coreutils"
    "cut:coreutils"
    "paste:coreutils"

    "ps:procps"
    "pgrep:procps"
    "kill:procps"
    "flock:util-linux"
    "tar:tar"
    "gzip:gzip"
    "zip:zip"
    "unzip:unzip"
    "jq:jq"

    "shellcheck:shellcheck"
    "shfmt:shfmt"
    "make:make"
    "gcc:gcc"
    "g++:g++"
    "cmake:cmake"
    "ctest:cmake"
    "xmake:xmake"

    "node:nodejs"
    "npm:npm"
    "npx:npm"
    "bun:bun"
    "pnpm:pnpm"
    "yarn:yarn"
    "tsc:typescript"
    "tsx:tsx"

    "python3:python3"
    "pip3:python3-pip"
    "uv:uv"
    "rustc:rustc"
    "cargo:cargo"
    "go:golang"
    "zig:zig"
    "php:php"
    "composer:composer"

    "dotnet:dotnet-sdk"
    "java:default-jre"
    "javac:default-jdk"
    "mvn:maven"
    "gradle:gradle"

    "lua:lua5.4"
    "luac:lua5.4"
    "luarocks:luarocks"
    "docker:docker.io"
    "docker-compose:docker-compose"
)
